//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrushFactory.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrushFactory.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush {0}.
        /// </summary>
        internal static string AbrBrushNameFallbackFormat {
            get {
                return ResourceManager.GetString("AbrBrushNameFallbackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ABR version: {0}.
        /// </summary>
        internal static string AbrUnsupportedMajorVersionFormat {
            get {
                return ResourceManager.GetString("AbrUnsupportedMajorVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ABR version: {0}.{1}.
        /// </summary>
        internal static string AbrUnsupportedMinorVersionFormat {
            get {
                return ResourceManager.GetString("AbrUnsupportedMinorVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brushes....
        /// </summary>
        internal static string AddBrushes {
            get {
                return ResourceManager.GetString("AddBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select additional brushes to add to the list..
        /// </summary>
        internal static string AddBrushesTip {
            get {
                return ResourceManager.GetString("AddBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a directory to add to the list of places to load custom brushes from..
        /// </summary>
        internal static string AddFolderTip {
            get {
                return ResourceManager.GetString("AddFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Transparency:.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush transparency shortcut: Ctrl + A + Mouse Wheel. Sets the brush transparency, so it becomes opaque or see-through..
        /// </summary>
        internal static string BrushAlphaTip {
            get {
                return ResourceManager.GetString("BrushAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string BrushColor {
            get {
                return ResourceManager.GetString("BrushColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you set the color of the brush..
        /// </summary>
        internal static string BrushColorTip {
            get {
                return ResourceManager.GetString("BrushColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Brush Directories To Auto-Load.
        /// </summary>
        internal static string BrushLocations {
            get {
                return ResourceManager.GetString("BrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places to look for brushes appear here. Type a new address or use &apos;add folder&apos; to add your own..
        /// </summary>
        internal static string BrushLocationsTextboxTip {
            get {
                return ResourceManager.GetString("BrushLocationsTextboxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc. brush options.
        /// </summary>
        internal static string BrushOptions {
            get {
                return ResourceManager.GetString("BrushOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush rotation shortcut: Ctrl + R + Mouse Wheel. Sets the brush rotation for tilting while drawing..
        /// </summary>
        internal static string BrushRotationTip {
            get {
                return ResourceManager.GetString("BrushRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you choose another brush to use..
        /// </summary>
        internal static string BrushSelectorTip {
            get {
                return ResourceManager.GetString("BrushSelectorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush size shortcut: Ctrl + S + Mouse Wheel. Sets the brush size to make it larger or smaller..
        /// </summary>
        internal static string BrushSizeTip {
            get {
                return ResourceManager.GetString("BrushSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the smoothing on each brush stroke. Low values are jagged and fast to compute. High values are smooth and slow (and possibly blurry)..
        /// </summary>
        internal static string BrushSmoothingTip {
            get {
                return ResourceManager.GetString("BrushSmoothingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving changes..
        /// </summary>
        internal static string CancelTip {
            get {
                return ResourceManager.GetString("CancelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Zoom:.
        /// </summary>
        internal static string CanvasZoom {
            get {
                return ResourceManager.GetString("CanvasZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas zoom shortcut: Ctrl + Mouse Wheel. Zooms the picture in and out to make editing easier..
        /// </summary>
        internal static string CanvasZoomTip {
            get {
                return ResourceManager.GetString("CanvasZoomTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Custom Brushes.
        /// </summary>
        internal static string ClearBrushes {
            get {
                return ResourceManager.GetString("ClearBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any custom brushes that were added. The normal brushes will remain..
        /// </summary>
        internal static string ClearBrushesTip {
            get {
                return ResourceManager.GetString("ClearBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        internal static string ClearSettings {
            get {
                return ResourceManager.GetString("ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all settings to the default values they had when the plugin first loaded..
        /// </summary>
        internal static string ClearSettingsTip {
            get {
                return ResourceManager.GetString("ClearSettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Blueness:.
        /// </summary>
        internal static string ColoringBlue {
            get {
                return ResourceManager.GetString("ColoringBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Greenness:.
        /// </summary>
        internal static string ColoringGreen {
            get {
                return ResourceManager.GetString("ColoringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Redness:.
        /// </summary>
        internal static string ColoringRed {
            get {
                return ResourceManager.GetString("ColoringRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize Brush.
        /// </summary>
        internal static string ColorizeBrush {
            get {
                return ResourceManager.GetString("ColorizeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the color of the brush is replaced by a solid color. Otherwise, the brush maintains its original colors and cannot use color shifting..
        /// </summary>
        internal static string ColorizeBrushTip {
            get {
                return ResourceManager.GetString("ColorizeBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Brush Locations.
        /// </summary>
        internal static string CustomBrushLocations {
            get {
                return ResourceManager.GetString("CustomBrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define where to look for brushes when this plugin loads..
        /// </summary>
        internal static string CustomBrushLocationsTip {
            get {
                return ResourceManager.GetString("CustomBrushLocationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle click and drag to pan image. Right-click for options. Hover over items for details..
        /// </summary>
        internal static string GeneralTooltip {
            get {
                return ResourceManager.GetString("GeneralTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default Brushes?.
        /// </summary>
        internal static string LoadDefaultBrushes {
            get {
                return ResourceManager.GetString("LoadDefaultBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned off, only the circle brush and any custom brushes will be loaded..
        /// </summary>
        internal static string LoadDefaultBrushesTip {
            get {
                return ResourceManager.GetString("LoadDefaultBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Alpha.
        /// </summary>
        internal static string LockAlpha {
            get {
                return ResourceManager.GetString("LockAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserves transparency so no brush strokes affect the transparency of the pixels..
        /// </summary>
        internal static string LockAlphaTip {
            get {
                return ResourceManager.GetString("LockAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize window?.
        /// </summary>
        internal static string MaximizeWindow {
            get {
                return ResourceManager.GetString("MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to maximize the window or not. Click to toggle..
        /// </summary>
        internal static string MaximizeWindowTip {
            get {
                return ResourceManager.GetString("MaximizeWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Draw Distance:.
        /// </summary>
        internal static string MinDrawDistance {
            get {
                return ResourceManager.GetString("MinDrawDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each brush stroke must be at least this far apart to have an effect. Used, for example, to make lines..
        /// </summary>
        internal static string MinDrawDistanceTip {
            get {
                return ResourceManager.GetString("MinDrawDistanceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and finish..
        /// </summary>
        internal static string OkTip {
            get {
                return ResourceManager.GetString("OkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate With Mouse.
        /// </summary>
        internal static string OrientToMouse {
            get {
                return ResourceManager.GetString("OrientToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the brush rotates with the mouse. If the brush appears to point to the right, it will look accurate. If it does not, try adjusting rotation to fix it..
        /// </summary>
        internal static string OrientToMouseTip {
            get {
                return ResourceManager.GetString("OrientToMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Spray:.
        /// </summary>
        internal static string RandHorzShift {
            get {
                return ResourceManager.GetString("RandHorzShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved left or right this much..
        /// </summary>
        internal static string RandHorzShiftTip {
            get {
                return ResourceManager.GetString("RandHorzShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Alpha:.
        /// </summary>
        internal static string RandMaxAlpha {
            get {
                return ResourceManager.GetString("RandMaxAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush transparency will randomly shift so it will sometimes be normal and sometimes up to this much more visible..
        /// </summary>
        internal static string RandMaxAlphaTip {
            get {
                return ResourceManager.GetString("RandMaxAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Blue:.
        /// </summary>
        internal static string RandMaxBlue {
            get {
                return ResourceManager.GetString("RandMaxBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much more blue..
        /// </summary>
        internal static string RandMaxBlueTip {
            get {
                return ResourceManager.GetString("RandMaxBlueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Green:.
        /// </summary>
        internal static string RandMaxGreen {
            get {
                return ResourceManager.GetString("RandMaxGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much more green..
        /// </summary>
        internal static string RandMaxGreenTip {
            get {
                return ResourceManager.GetString("RandMaxGreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Red:.
        /// </summary>
        internal static string RandMaxRed {
            get {
                return ResourceManager.GetString("RandMaxRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much more red..
        /// </summary>
        internal static string RandMaxRedTip {
            get {
                return ResourceManager.GetString("RandMaxRedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Size:.
        /// </summary>
        internal static string RandMaxSize {
            get {
                return ResourceManager.GetString("RandMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much bigger..
        /// </summary>
        internal static string RandMaxSizeTip {
            get {
                return ResourceManager.GetString("RandMaxSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Alpha:.
        /// </summary>
        internal static string RandMinAlpha {
            get {
                return ResourceManager.GetString("RandMinAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush transparency will randomly shift so it will sometimes be normal and sometimes up to this much more transparent..
        /// </summary>
        internal static string RandMinAlphaTip {
            get {
                return ResourceManager.GetString("RandMinAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Blue:.
        /// </summary>
        internal static string RandMinBlue {
            get {
                return ResourceManager.GetString("RandMinBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much less blue..
        /// </summary>
        internal static string RandMinBlueTip {
            get {
                return ResourceManager.GetString("RandMinBlueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Green:.
        /// </summary>
        internal static string RandMinGreen {
            get {
                return ResourceManager.GetString("RandMinGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much less green..
        /// </summary>
        internal static string RandMinGreenTip {
            get {
                return ResourceManager.GetString("RandMinGreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Red:.
        /// </summary>
        internal static string RandMinRed {
            get {
                return ResourceManager.GetString("RandMinRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much less red..
        /// </summary>
        internal static string RandMinRedTip {
            get {
                return ResourceManager.GetString("RandMinRedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Size:.
        /// </summary>
        internal static string RandMinSize {
            get {
                return ResourceManager.GetString("RandMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much smaller..
        /// </summary>
        internal static string RandMinSizeTip {
            get {
                return ResourceManager.GetString("RandMinSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Left:.
        /// </summary>
        internal static string RandRotLeft {
            get {
                return ResourceManager.GetString("RandRotLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the left..
        /// </summary>
        internal static string RandRotLeftTip {
            get {
                return ResourceManager.GetString("RandRotLeftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Right:.
        /// </summary>
        internal static string RandRotRight {
            get {
                return ResourceManager.GetString("RandRotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the right..
        /// </summary>
        internal static string RandRotRightTip {
            get {
                return ResourceManager.GetString("RandRotRightTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spray:.
        /// </summary>
        internal static string RandVertShift {
            get {
                return ResourceManager.GetString("RandVertShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved up or down this much..
        /// </summary>
        internal static string RandVertShiftTip {
            get {
                return ResourceManager.GetString("RandVertShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Shortcut: Ctrl + Y. Restores changes removed by undo, if possible..
        /// </summary>
        internal static string RedoTip {
            get {
                return ResourceManager.GetString("RedoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Rotation:.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all changes in the preferences..
        /// </summary>
        internal static string SavePreferencesTip {
            get {
                return ResourceManager.GetString("SavePreferencesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Shift:.
        /// </summary>
        internal static string ShiftAlpha {
            get {
                return ResourceManager.GetString("ShiftAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will change transparency by this much..
        /// </summary>
        internal static string ShiftAlphaTip {
            get {
                return ResourceManager.GetString("ShiftAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Shift:.
        /// </summary>
        internal static string ShiftRotation {
            get {
                return ResourceManager.GetString("ShiftRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will tilt by this much..
        /// </summary>
        internal static string ShiftRotationTip {
            get {
                return ResourceManager.GetString("ShiftRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Shift:.
        /// </summary>
        internal static string ShiftSize {
            get {
                return ResourceManager.GetString("ShiftSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush size will change by this much..
        /// </summary>
        internal static string ShiftSizeTip {
            get {
                return ResourceManager.GetString("ShiftSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush can be mirrored horizontally and/or vertically..
        /// </summary>
        internal static string SymmetryTip {
            get {
                return ResourceManager.GetString("SymmetryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string TabColor {
            get {
                return ResourceManager.GetString("TabColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string TabControls {
            get {
                return ResourceManager.GetString("TabControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter.
        /// </summary>
        internal static string TabJitter {
            get {
                return ResourceManager.GetString("TabJitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string TabOther {
            get {
                return ResourceManager.GetString("TabOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Factory.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Shortcut: Ctrl + Z. Undo the last drawing, if possible..
        /// </summary>
        internal static string UndoTip {
            get {
                return ResourceManager.GetString("UndoTip", resourceCulture);
            }
        }
    }
}
