//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrushFactory.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrushFactory.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush {0}.
        /// </summary>
        internal static string AbrBrushNameFallbackFormat {
            get {
                return ResourceManager.GetString("AbrBrushNameFallbackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ABR version: {0}.
        /// </summary>
        internal static string AbrUnsupportedMajorVersionFormat {
            get {
                return ResourceManager.GetString("AbrUnsupportedMajorVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ABR version: {0}.{1}.
        /// </summary>
        internal static string AbrUnsupportedMinorVersionFormat {
            get {
                return ResourceManager.GetString("AbrUnsupportedMinorVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string AccordionBrush {
            get {
                return ResourceManager.GetString("AccordionBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter - Basics.
        /// </summary>
        internal static string AccordionJitterBasics {
            get {
                return ResourceManager.GetString("AccordionJitterBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter - Color.
        /// </summary>
        internal static string AccordionJitterColor {
            get {
                return ResourceManager.GetString("AccordionJitterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string AccordionSettings {
            get {
                return ResourceManager.GetString("AccordionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift - Basics.
        /// </summary>
        internal static string AccordionShiftBasics {
            get {
                return ResourceManager.GetString("AccordionShiftBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Settings.
        /// </summary>
        internal static string AccordionSpecialSettings {
            get {
                return ResourceManager.GetString("AccordionSpecialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet - Assign Pressure.
        /// </summary>
        internal static string AccordionTabPressureControls {
            get {
                return ResourceManager.GetString("AccordionTabPressureControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brushes....
        /// </summary>
        internal static string AddBrushes {
            get {
                return ResourceManager.GetString("AddBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select additional brushes to add to the list..
        /// </summary>
        internal static string AddBrushesTip {
            get {
                return ResourceManager.GetString("AddBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a directory to add to the list of places to load custom brushes from..
        /// </summary>
        internal static string AddFolderTip {
            get {
                return ResourceManager.GetString("AddFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Transparency:.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush transparency shortcut: Ctrl + A + Mouse Wheel. Sets the brush transparency, so it becomes opaque or see-through..
        /// </summary>
        internal static string BrushAlphaTip {
            get {
                return ResourceManager.GetString("BrushAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string BrushColor {
            get {
                return ResourceManager.GetString("BrushColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you set the color of the brush..
        /// </summary>
        internal static string BrushColorTip {
            get {
                return ResourceManager.GetString("BrushColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Stroke Density:.
        /// </summary>
        internal static string BrushDensity {
            get {
                return ResourceManager.GetString("BrushDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how often the brush is applied while drawing. Set to 0 to turn off. When minimum draw distance is set high, this draws lines..
        /// </summary>
        internal static string BrushDensityTip {
            get {
                return ResourceManager.GetString("BrushDensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Brush Directories To Auto-Load.
        /// </summary>
        internal static string BrushLocations {
            get {
                return ResourceManager.GetString("BrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places to look for brushes appear here. Type a new address or use &apos;add folder&apos; to add your own..
        /// </summary>
        internal static string BrushLocationsTextboxTip {
            get {
                return ResourceManager.GetString("BrushLocationsTextboxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush rotation shortcut: Ctrl + R + Mouse Wheel. Sets the brush rotation for tilting while drawing..
        /// </summary>
        internal static string BrushRotationTip {
            get {
                return ResourceManager.GetString("BrushRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you choose another brush to use..
        /// </summary>
        internal static string BrushSelectorTip {
            get {
                return ResourceManager.GetString("BrushSelectorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush size shortcut: Ctrl + S + Mouse Wheel. Sets the brush size to make it larger or smaller..
        /// </summary>
        internal static string BrushSizeTip {
            get {
                return ResourceManager.GetString("BrushSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the smoothing on each brush stroke. Low values are jagged and fast to compute. High values are smooth and slow (and possibly blurry)..
        /// </summary>
        internal static string BrushSmoothingTip {
            get {
                return ResourceManager.GetString("BrushSmoothingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving changes..
        /// </summary>
        internal static string CancelTip {
            get {
                return ResourceManager.GetString("CancelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom brushes couldn&apos;t be loaded. You can try defining them again..
        /// </summary>
        internal static string CannotLoadSettingsError {
            get {
                return ResourceManager.GetString("CannotLoadSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Zoom:.
        /// </summary>
        internal static string CanvasZoom {
            get {
                return ResourceManager.GetString("CanvasZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas zoom shortcut: Ctrl + Mouse Wheel. Zooms the picture in and out to make editing easier..
        /// </summary>
        internal static string CanvasZoomTip {
            get {
                return ResourceManager.GetString("CanvasZoomTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Custom Brushes.
        /// </summary>
        internal static string ClearBrushes {
            get {
                return ResourceManager.GetString("ClearBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any custom brushes that were added. The normal brushes will remain..
        /// </summary>
        internal static string ClearBrushesTip {
            get {
                return ResourceManager.GetString("ClearBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        internal static string ClearSettings {
            get {
                return ResourceManager.GetString("ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all settings to the default values they had when the plugin first loaded..
        /// </summary>
        internal static string ClearSettingsTip {
            get {
                return ResourceManager.GetString("ClearSettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize Brush.
        /// </summary>
        internal static string ColorizeBrush {
            get {
                return ResourceManager.GetString("ColorizeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the color of the brush is replaced by a solid color. Otherwise, the brush maintains its original colors and cannot use color shifting..
        /// </summary>
        internal static string ColorizeBrushTip {
            get {
                return ResourceManager.GetString("ColorizeBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker Shortcut: K. Activate this tool to select a color on-screen, and switch to the last-used tool afterwards..
        /// </summary>
        internal static string ColorPickerTip {
            get {
                return ResourceManager.GetString("ColorPickerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Brush Locations.
        /// </summary>
        internal static string CustomBrushLocations {
            get {
                return ResourceManager.GetString("CustomBrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define where to look for brushes when this plugin loads..
        /// </summary>
        internal static string CustomBrushLocationsTip {
            get {
                return ResourceManager.GetString("CustomBrushLocationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Dots.
        /// </summary>
        internal static string DefaultBrushBigDots {
            get {
                return ResourceManager.GetString("DefaultBrushBigDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Light 256px.
        /// </summary>
        internal static string DefaultBrushCircle {
            get {
                return ResourceManager.GetString("DefaultBrushCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Hard 256px.
        /// </summary>
        internal static string DefaultBrushCircleHard {
            get {
                return ResourceManager.GetString("DefaultBrushCircleHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Med 256px.
        /// </summary>
        internal static string DefaultBrushCircleMed {
            get {
                return ResourceManager.GetString("DefaultBrushCircleMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rough.
        /// </summary>
        internal static string DefaultBrushCircleRough {
            get {
                return ResourceManager.GetString("DefaultBrushCircleRough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmented.
        /// </summary>
        internal static string DefaultBrushCircleSegmented {
            get {
                return ResourceManager.GetString("DefaultBrushCircleSegmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketchy.
        /// </summary>
        internal static string DefaultBrushCircleSketchy {
            get {
                return ResourceManager.GetString("DefaultBrushCircleSketchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cracks.
        /// </summary>
        internal static string DefaultBrushCracks {
            get {
                return ResourceManager.GetString("DefaultBrushCracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt.
        /// </summary>
        internal static string DefaultBrushDirt {
            get {
                return ResourceManager.GetString("DefaultBrushDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt 2.
        /// </summary>
        internal static string DefaultBrushDirt2 {
            get {
                return ResourceManager.GetString("DefaultBrushDirt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt 3.
        /// </summary>
        internal static string DefaultBrushDirt3 {
            get {
                return ResourceManager.GetString("DefaultBrushDirt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal.
        /// </summary>
        internal static string DefaultBrushFractalDirt {
            get {
                return ResourceManager.GetString("DefaultBrushFractalDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        internal static string DefaultBrushGrass {
            get {
                return ResourceManager.GetString("DefaultBrushGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        internal static string DefaultBrushGravel {
            get {
                return ResourceManager.GetString("DefaultBrushGravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string DefaultBrushLine {
            get {
                return ResourceManager.GetString("DefaultBrushLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        internal static string DefaultBrushRain {
            get {
                return ResourceManager.GetString("DefaultBrushRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales.
        /// </summary>
        internal static string DefaultBrushScales {
            get {
                return ResourceManager.GetString("DefaultBrushScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Dots.
        /// </summary>
        internal static string DefaultBrushSmallDots {
            get {
                return ResourceManager.GetString("DefaultBrushSmallDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        internal static string DefaultBrushSmoke {
            get {
                return ResourceManager.GetString("DefaultBrushSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark.
        /// </summary>
        internal static string DefaultBrushSpark {
            get {
                return ResourceManager.GetString("DefaultBrushSpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiral.
        /// </summary>
        internal static string DefaultBrushSpiral {
            get {
                return ResourceManager.GetString("DefaultBrushSpiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Jitter:.
        /// </summary>
        internal static string JitterBlue {
            get {
                return ResourceManager.GetString("JitterBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much less or more blue..
        /// </summary>
        internal static string JitterBlueTip {
            get {
                return ResourceManager.GetString("JitterBlueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Jitter:.
        /// </summary>
        internal static string JitterGreen {
            get {
                return ResourceManager.GetString("JitterGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much less or more green..
        /// </summary>
        internal static string JitterGreenTip {
            get {
                return ResourceManager.GetString("JitterGreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Jitter:.
        /// </summary>
        internal static string JitterHue {
            get {
                return ResourceManager.GetString("JitterHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush&apos;s hue will randomly shift based on the provided amounts..
        /// </summary>
        internal static string JitterHueTip {
            get {
                return ResourceManager.GetString("JitterHueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Jitter:.
        /// </summary>
        internal static string JitterRed {
            get {
                return ResourceManager.GetString("JitterRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift so it will sometimes be normal and sometimes up to this much less or more red..
        /// </summary>
        internal static string JitterRedTip {
            get {
                return ResourceManager.GetString("JitterRedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat. Jitter:.
        /// </summary>
        internal static string JitterSaturation {
            get {
                return ResourceManager.GetString("JitterSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush&apos;s grayness will randomly shift based on the provided amounts..
        /// </summary>
        internal static string JitterSaturationTip {
            get {
                return ResourceManager.GetString("JitterSaturationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Jitter:.
        /// </summary>
        internal static string JitterValue {
            get {
                return ResourceManager.GetString("JitterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush color will randomly shift based on the provided amounts..
        /// </summary>
        internal static string JitterValueTip {
            get {
                return ResourceManager.GetString("JitterValueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default Brushes?.
        /// </summary>
        internal static string LoadDefaultBrushes {
            get {
                return ResourceManager.GetString("LoadDefaultBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned off, only the circle brush and any custom brushes will be loaded..
        /// </summary>
        internal static string LoadDefaultBrushesTip {
            get {
                return ResourceManager.GetString("LoadDefaultBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Alpha.
        /// </summary>
        internal static string LockAlpha {
            get {
                return ResourceManager.GetString("LockAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserves transparency so no brush strokes affect the transparency of the pixels..
        /// </summary>
        internal static string LockAlphaTip {
            get {
                return ResourceManager.GetString("LockAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize window?.
        /// </summary>
        internal static string MaximizeWindow {
            get {
                return ResourceManager.GetString("MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to maximize the window or not. Click to toggle..
        /// </summary>
        internal static string MaximizeWindowTip {
            get {
                return ResourceManager.GetString("MaximizeWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Draw Distance:.
        /// </summary>
        internal static string MinDrawDistance {
            get {
                return ResourceManager.GetString("MinDrawDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each brush stroke must be at least this far apart to have an effect. Used, for example, to make lines. Draws lines when set to high values when brush density is not zero..
        /// </summary>
        internal static string MinDrawDistanceTip {
            get {
                return ResourceManager.GetString("MinDrawDistanceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and finish..
        /// </summary>
        internal static string OkTip {
            get {
                return ResourceManager.GetString("OkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate With Mouse.
        /// </summary>
        internal static string OrientToMouse {
            get {
                return ResourceManager.GetString("OrientToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the brush rotates with the mouse. If the brush appears to point to the right, it will look accurate. If it does not, try adjusting rotation to fix it..
        /// </summary>
        internal static string OrientToMouseTip {
            get {
                return ResourceManager.GetString("OrientToMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Spray:.
        /// </summary>
        internal static string RandHorzShift {
            get {
                return ResourceManager.GetString("RandHorzShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved left or right this much..
        /// </summary>
        internal static string RandHorzShiftTip {
            get {
                return ResourceManager.GetString("RandHorzShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Size:.
        /// </summary>
        internal static string RandMaxSize {
            get {
                return ResourceManager.GetString("RandMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much bigger..
        /// </summary>
        internal static string RandMaxSizeTip {
            get {
                return ResourceManager.GetString("RandMaxSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Alpha:.
        /// </summary>
        internal static string RandMinAlpha {
            get {
                return ResourceManager.GetString("RandMinAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush transparency will randomly shift so it will sometimes be normal and sometimes up to this much more transparent..
        /// </summary>
        internal static string RandMinAlphaTip {
            get {
                return ResourceManager.GetString("RandMinAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Size:.
        /// </summary>
        internal static string RandMinSize {
            get {
                return ResourceManager.GetString("RandMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much smaller..
        /// </summary>
        internal static string RandMinSizeTip {
            get {
                return ResourceManager.GetString("RandMinSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Left:.
        /// </summary>
        internal static string RandRotLeft {
            get {
                return ResourceManager.GetString("RandRotLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the left..
        /// </summary>
        internal static string RandRotLeftTip {
            get {
                return ResourceManager.GetString("RandRotLeftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Right:.
        /// </summary>
        internal static string RandRotRight {
            get {
                return ResourceManager.GetString("RandRotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the right..
        /// </summary>
        internal static string RandRotRightTip {
            get {
                return ResourceManager.GetString("RandRotRightTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spray:.
        /// </summary>
        internal static string RandVertShift {
            get {
                return ResourceManager.GetString("RandVertShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved up or down this much..
        /// </summary>
        internal static string RandVertShiftTip {
            get {
                return ResourceManager.GetString("RandVertShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Shortcut: Ctrl + Y. Restores changes removed by undo, if possible..
        /// </summary>
        internal static string RedoTip {
            get {
                return ResourceManager.GetString("RedoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Rotation:.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all changes in the preferences..
        /// </summary>
        internal static string SavePreferencesTip {
            get {
                return ResourceManager.GetString("SavePreferencesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings folder could not be located. Your settings may not be loaded or saved..
        /// </summary>
        internal static string SettingsUnavailableError {
            get {
                return ResourceManager.GetString("SettingsUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Shift:.
        /// </summary>
        internal static string ShiftAlpha {
            get {
                return ResourceManager.GetString("ShiftAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will change transparency by this much..
        /// </summary>
        internal static string ShiftAlphaTip {
            get {
                return ResourceManager.GetString("ShiftAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Shift:.
        /// </summary>
        internal static string ShiftRotation {
            get {
                return ResourceManager.GetString("ShiftRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will tilt by this much..
        /// </summary>
        internal static string ShiftRotationTip {
            get {
                return ResourceManager.GetString("ShiftRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Shift:.
        /// </summary>
        internal static string ShiftSize {
            get {
                return ResourceManager.GetString("ShiftSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush size will change by this much..
        /// </summary>
        internal static string ShiftSizeTip {
            get {
                return ResourceManager.GetString("ShiftSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing: High.
        /// </summary>
        internal static string SmoothingHigh {
            get {
                return ResourceManager.GetString("SmoothingHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing: Jagged.
        /// </summary>
        internal static string SmoothingJagged {
            get {
                return ResourceManager.GetString("SmoothingJagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing: Normal.
        /// </summary>
        internal static string SmoothingNormal {
            get {
                return ResourceManager.GetString("SmoothingNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 10-point.
        /// </summary>
        internal static string Symmetry10pt {
            get {
                return ResourceManager.GetString("Symmetry10pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 11-point.
        /// </summary>
        internal static string Symmetry11pt {
            get {
                return ResourceManager.GetString("Symmetry11pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 12-point.
        /// </summary>
        internal static string Symmetry12pt {
            get {
                return ResourceManager.GetString("Symmetry12pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 3-point.
        /// </summary>
        internal static string Symmetry3pt {
            get {
                return ResourceManager.GetString("Symmetry3pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 4-point.
        /// </summary>
        internal static string Symmetry4pt {
            get {
                return ResourceManager.GetString("Symmetry4pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 5-point.
        /// </summary>
        internal static string Symmetry5pt {
            get {
                return ResourceManager.GetString("Symmetry5pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 6-point.
        /// </summary>
        internal static string Symmetry6pt {
            get {
                return ResourceManager.GetString("Symmetry6pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 7-point.
        /// </summary>
        internal static string Symmetry7pt {
            get {
                return ResourceManager.GetString("Symmetry7pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 8-point.
        /// </summary>
        internal static string Symmetry8pt {
            get {
                return ResourceManager.GetString("Symmetry8pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 9-point.
        /// </summary>
        internal static string Symmetry9pt {
            get {
                return ResourceManager.GetString("Symmetry9pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: Both.
        /// </summary>
        internal static string SymmetryBoth {
            get {
                return ResourceManager.GetString("SymmetryBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: Horizontal.
        /// </summary>
        internal static string SymmetryHorizontal {
            get {
                return ResourceManager.GetString("SymmetryHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: None.
        /// </summary>
        internal static string SymmetryNone {
            get {
                return ResourceManager.GetString("SymmetryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: At Points.
        /// </summary>
        internal static string SymmetrySetPoints {
            get {
                return ResourceManager.GetString("SymmetrySetPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush can be mirrored horizontally and/or vertically..
        /// </summary>
        internal static string SymmetryTip {
            get {
                return ResourceManager.GetString("SymmetryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: Vertical.
        /// </summary>
        internal static string SymmetryVertical {
            get {
                return ResourceManager.GetString("SymmetryVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Factory.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Shortcut: B. Activate this tool to draw with the chosen brush and its settings..
        /// </summary>
        internal static string ToolBrushTip {
            get {
                return ResourceManager.GetString("ToolBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser Shortcut: E. Activate this tool to erase with the chosen brush and its settings, revealing the original image..
        /// </summary>
        internal static string ToolEraserTip {
            get {
                return ResourceManager.GetString("ToolEraserTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Origin Shortcut: O. Activate this tool to change the symmetry origin..
        /// </summary>
        internal static string ToolOriginTip {
            get {
                return ResourceManager.GetString("ToolOriginTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Shortcut: Ctrl + Z. Undo the last drawing, if possible..
        /// </summary>
        internal static string UndoTip {
            get {
                return ResourceManager.GetString("UndoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as number.
        /// </summary>
        internal static string ValueTypeAdd {
            get {
                return ResourceManager.GetString("ValueTypeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as percent of max.
        /// </summary>
        internal static string ValueTypeAddPercent {
            get {
                return ResourceManager.GetString("ValueTypeAddPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as percent of self.
        /// </summary>
        internal static string ValueTypeAddPercentCurrent {
            get {
                return ResourceManager.GetString("ValueTypeAddPercentCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the percent of max.
        /// </summary>
        internal static string ValueTypeMatchPercent {
            get {
                return ResourceManager.GetString("ValueTypeMatchPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the number.
        /// </summary>
        internal static string ValueTypeMatchValue {
            get {
                return ResourceManager.GetString("ValueTypeMatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in use.
        /// </summary>
        internal static string ValueTypeNothing {
            get {
                return ResourceManager.GetString("ValueTypeNothing", resourceCulture);
            }
        }
    }
}
