//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDraw.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicDraw.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush {0}.
        /// </summary>
        internal static string AbrBrushNameFallbackFormat {
            get {
                return ResourceManager.GetString("AbrBrushNameFallbackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ABR version: {0}.
        /// </summary>
        internal static string AbrUnsupportedMajorVersionFormat {
            get {
                return ResourceManager.GetString("AbrUnsupportedMajorVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ABR version: {0}.{1}.
        /// </summary>
        internal static string AbrUnsupportedMinorVersionFormat {
            get {
                return ResourceManager.GetString("AbrUnsupportedMinorVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string AccordionBrush {
            get {
                return ResourceManager.GetString("AccordionBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter - Basics.
        /// </summary>
        internal static string AccordionJitterBasics {
            get {
                return ResourceManager.GetString("AccordionJitterBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter - Color.
        /// </summary>
        internal static string AccordionJitterColor {
            get {
                return ResourceManager.GetString("AccordionJitterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings - Brush.
        /// </summary>
        internal static string AccordionSettingsBrush {
            get {
                return ResourceManager.GetString("AccordionSettingsBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift - Basics.
        /// </summary>
        internal static string AccordionShiftBasics {
            get {
                return ResourceManager.GetString("AccordionShiftBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Settings.
        /// </summary>
        internal static string AccordionSpecialSettings {
            get {
                return ResourceManager.GetString("AccordionSpecialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet - Assign Pressure.
        /// </summary>
        internal static string AccordionTabPressureControls {
            get {
                return ResourceManager.GetString("AccordionTabPressureControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brush Images.
        /// </summary>
        internal static string AddBrushImages {
            get {
                return ResourceManager.GetString("AddBrushImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select additional brush images to permanently add. They can be removed later from custom brush locations (under Special Settings)..
        /// </summary>
        internal static string AddBrushImagesTip {
            get {
                return ResourceManager.GetString("AddBrushImagesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        internal static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for files to load as custom brush images when Dynamic Draw starts..
        /// </summary>
        internal static string AddFilesTip {
            get {
                return ResourceManager.GetString("AddFilesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a folder to add to the list of places to load custom brush images from. All images directly within the folder will be loaded when Dynamic Draw starts. Images in sub-folders will not..
        /// </summary>
        internal static string AddFoldersTip {
            get {
                return ResourceManager.GetString("AddFoldersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Transparency:.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto manage density.
        /// </summary>
        internal static string AutomaticBrushDensity {
            get {
                return ResourceManager.GetString("AutomaticBrushDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is toggled on, the density will automatically adjust based on the brush size to ensure a smooth line at any brush size..
        /// </summary>
        internal static string AutomaticBrushDensityTip {
            get {
                return ResourceManager.GetString("AutomaticBrushDensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use black background.
        /// </summary>
        internal static string BackgroundBlack {
            get {
                return ResourceManager.GetString("BackgroundBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the clipboard image as background.
        /// </summary>
        internal static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use no background (a little faster).
        /// </summary>
        internal static string BackgroundNone {
            get {
                return ResourceManager.GetString("BackgroundNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use transparent background (checkered).
        /// </summary>
        internal static string BackgroundTransparent {
            get {
                return ResourceManager.GetString("BackgroundTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use white background.
        /// </summary>
        internal static string BackgroundWhite {
            get {
                return ResourceManager.GetString("BackgroundWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blending: Normal.
        /// </summary>
        internal static string BlendModeNormal {
            get {
                return ResourceManager.GetString("BlendModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blending: Overwrite.
        /// </summary>
        internal static string BlendModeOverwrite {
            get {
                return ResourceManager.GetString("BlendModeOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend modes describe how pixels should be edited by the brush stroke.
        ///Normal: brushing draws over the image as usual, never making an image more transparent.
        ///Overwrite: brushing draws over the image as usual, except it also replaces transparency to whatever is set..
        /// </summary>
        internal static string BlendModeTip {
            get {
                return ResourceManager.GetString("BlendModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush transparency shortcut: Ctrl + A + Mouse Wheel. Sets the brush transparency, so it becomes opaque or see-through..
        /// </summary>
        internal static string BrushAlphaTip {
            get {
                return ResourceManager.GetString("BrushAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string BrushColor {
            get {
                return ResourceManager.GetString("BrushColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you set the color of the brush..
        /// </summary>
        internal static string BrushColorTip {
            get {
                return ResourceManager.GetString("BrushColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Stroke Density:.
        /// </summary>
        internal static string BrushDensity {
            get {
                return ResourceManager.GetString("BrushDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how often the brush is applied while drawing. Set to 0 to turn off. When minimum draw distance is set high, this draws lines..
        /// </summary>
        internal static string BrushDensityTip {
            get {
                return ResourceManager.GetString("BrushDensityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you choose another brush image to use..
        /// </summary>
        internal static string BrushImageSelectorTip {
            get {
                return ResourceManager.GetString("BrushImageSelectorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush image directories and files to load when Dynamic Draw starts.
        /// </summary>
        internal static string BrushLocations {
            get {
                return ResourceManager.GetString("BrushLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places to look for brush images appear here. Type a new address or use &apos;add folder&apos; to add your own..
        /// </summary>
        internal static string BrushLocationsTextboxTip {
            get {
                return ResourceManager.GetString("BrushLocationsTextboxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush rotation shortcut: Ctrl + R + Mouse Wheel. Sets the brush rotation for tilting while drawing..
        /// </summary>
        internal static string BrushRotationTip {
            get {
                return ResourceManager.GetString("BrushRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you choose another brush to use. A brush is a collection of all the settings (size, jitter options, tablet behavior) that affects drawing, including which image is chosen..
        /// </summary>
        internal static string BrushSelectorTip {
            get {
                return ResourceManager.GetString("BrushSelectorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush size shortcut: Ctrl + S + Mouse Wheel. Sets the brush size to make it larger or smaller..
        /// </summary>
        internal static string BrushSizeTip {
            get {
                return ResourceManager.GetString("BrushSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the smoothing on each brush stroke. Low values are jagged and fast to compute. High values are smooth and slow (and possibly blurry)..
        /// </summary>
        internal static string BrushSmoothingTip {
            get {
                return ResourceManager.GetString("BrushSmoothingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in.
        /// </summary>
        internal static string BuiltIn {
            get {
                return ResourceManager.GetString("BuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset - Airbrush.
        /// </summary>
        internal static string BuiltInBrushAirbrush {
            get {
                return ResourceManager.GetString("BuiltInBrushAirbrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset - Grass.
        /// </summary>
        internal static string BuiltInBrushGrass {
            get {
                return ResourceManager.GetString("BuiltInBrushGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset - Pencil.
        /// </summary>
        internal static string BuiltInBrushPencil {
            get {
                return ResourceManager.GetString("BuiltInBrushPencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset - Recolor.
        /// </summary>
        internal static string BuiltInBrushRecolor {
            get {
                return ResourceManager.GetString("BuiltInBrushRecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without saving changes..
        /// </summary>
        internal static string CancelTip {
            get {
                return ResourceManager.GetString("CancelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom brush images couldn&apos;t be loaded. You can try defining them again..
        /// </summary>
        internal static string CannotLoadSettingsError {
            get {
                return ResourceManager.GetString("CannotLoadSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Angle:.
        /// </summary>
        internal static string CanvasAngle {
            get {
                return ResourceManager.GetString("CanvasAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas angle shortcuts: Shift + Mouse Wheel, and Shift + Left/Right Arrow. Rotates the canvas around its center (this is mainly useful with a tablet).
        ///
        ///Press Zero to reset the canvas position, zoom and angle..
        /// </summary>
        internal static string CanvasAngleTip {
            get {
                return ResourceManager.GetString("CanvasAngleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angle of the canvas. Rotating it can be useful to tablet users who draw better at certain angles..
        /// </summary>
        internal static string CanvasRotation {
            get {
                return ResourceManager.GetString("CanvasRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horizontal position of the canvas. Changing this moves it left and right..
        /// </summary>
        internal static string CanvasX {
            get {
                return ResourceManager.GetString("CanvasX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertical position of the canvas. Changing this moves it up and down..
        /// </summary>
        internal static string CanvasY {
            get {
                return ResourceManager.GetString("CanvasY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Zoom:.
        /// </summary>
        internal static string CanvasZoom {
            get {
                return ResourceManager.GetString("CanvasZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas zoom shortcut: Ctrl + Mouse Wheel. Zooms the picture in and out to make editing easier.
        ///
        ///Press Zero to reset the canvas position, zoom and angle..
        /// </summary>
        internal static string CanvasZoomTip {
            get {
                return ResourceManager.GetString("CanvasZoomTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Current Brush Settings.
        /// </summary>
        internal static string ClearSettings {
            get {
                return ResourceManager.GetString("ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all temporary changes to the current brush settings..
        /// </summary>
        internal static string ClearSettingsTip {
            get {
                return ResourceManager.GetString("ClearSettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not use clipboard image..
        /// </summary>
        internal static string ClipboardErrorUnusable {
            get {
                return ResourceManager.GetString("ClipboardErrorUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Color:.
        /// </summary>
        internal static string ColorInfluence {
            get {
                return ResourceManager.GetString("ColorInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the active color affects the hue of the brush stroke..
        /// </summary>
        internal static string ColorInfluenceHTip {
            get {
                return ResourceManager.GetString("ColorInfluenceHTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the active color affects the saturation (grayness) of the brush stroke..
        /// </summary>
        internal static string ColorInfluenceSTip {
            get {
                return ResourceManager.GetString("ColorInfluenceSTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the regular brush image colors are used at 0%. Only the active color is used at 100%. For values between, the active color is mixed into the brush image..
        /// </summary>
        internal static string ColorInfluenceTip {
            get {
                return ResourceManager.GetString("ColorInfluenceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the active color affects the value (brightness) of the brush stroke..
        /// </summary>
        internal static string ColorInfluenceVTip {
            get {
                return ResourceManager.GetString("ColorInfluenceVTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Mixing.
        /// </summary>
        internal static string ColorizeBrush {
            get {
                return ResourceManager.GetString("ColorizeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the brush image is replaced entirely with a solid color. When off, the original brush color will be used with options to influence it using the active color..
        /// </summary>
        internal static string ColorizeBrushTip {
            get {
                return ResourceManager.GetString("ColorizeBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker Shortcut: K. Activate this tool to select a color on-screen, and switch to the last-used tool afterwards..
        /// </summary>
        internal static string ColorPickerTip {
            get {
                return ResourceManager.GetString("ColorPickerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes and return to Paint.Net?.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and return to Paint.Net?.
        /// </summary>
        internal static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a unique name for the brush below. All brush-related settings will be saved as part of this brush, except which brush images are loaded (although the selected image will be saved)..
        /// </summary>
        internal static string CustomBrushDialogDescription {
            get {
                return ResourceManager.GetString("CustomBrushDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brush name is required unless you cancel the dialog..
        /// </summary>
        internal static string CustomBrushDialogErrorName {
            get {
                return ResourceManager.GetString("CustomBrushDialogErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom brush.
        /// </summary>
        internal static string CustomBrushDialogTitle {
            get {
                return ResourceManager.GetString("CustomBrushDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Image Locations.
        /// </summary>
        internal static string CustomBrushImageLocations {
            get {
                return ResourceManager.GetString("CustomBrushImageLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define where to look for brush images when this plugin loads..
        /// </summary>
        internal static string CustomBrushImageLocationsTip {
            get {
                return ResourceManager.GetString("CustomBrushImageLocationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images and abr brushes.
        /// </summary>
        internal static string CustomBrushImagesDirectoryFilter {
            get {
                return ResourceManager.GetString("CustomBrushImagesDirectoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load custom brush images.
        /// </summary>
        internal static string CustomBrushImagesDirectoryTitle {
            get {
                return ResourceManager.GetString("CustomBrushImagesDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Dots.
        /// </summary>
        internal static string DefaultBrushBigDots {
            get {
                return ResourceManager.GetString("DefaultBrushBigDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Light.
        /// </summary>
        internal static string DefaultBrushCircle {
            get {
                return ResourceManager.GetString("DefaultBrushCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Hard.
        /// </summary>
        internal static string DefaultBrushCircleHard {
            get {
                return ResourceManager.GetString("DefaultBrushCircleHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Med.
        /// </summary>
        internal static string DefaultBrushCircleMed {
            get {
                return ResourceManager.GetString("DefaultBrushCircleMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rough.
        /// </summary>
        internal static string DefaultBrushCircleRough {
            get {
                return ResourceManager.GetString("DefaultBrushCircleRough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmented.
        /// </summary>
        internal static string DefaultBrushCircleSegmented {
            get {
                return ResourceManager.GetString("DefaultBrushCircleSegmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketchy.
        /// </summary>
        internal static string DefaultBrushCircleSketchy {
            get {
                return ResourceManager.GetString("DefaultBrushCircleSketchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cracks.
        /// </summary>
        internal static string DefaultBrushCracks {
            get {
                return ResourceManager.GetString("DefaultBrushCracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt.
        /// </summary>
        internal static string DefaultBrushDirt {
            get {
                return ResourceManager.GetString("DefaultBrushDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt 2.
        /// </summary>
        internal static string DefaultBrushDirt2 {
            get {
                return ResourceManager.GetString("DefaultBrushDirt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt 3.
        /// </summary>
        internal static string DefaultBrushDirt3 {
            get {
                return ResourceManager.GetString("DefaultBrushDirt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal.
        /// </summary>
        internal static string DefaultBrushFractalDirt {
            get {
                return ResourceManager.GetString("DefaultBrushFractalDirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        internal static string DefaultBrushGrass {
            get {
                return ResourceManager.GetString("DefaultBrushGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        internal static string DefaultBrushGravel {
            get {
                return ResourceManager.GetString("DefaultBrushGravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string DefaultBrushLine {
            get {
                return ResourceManager.GetString("DefaultBrushLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        internal static string DefaultBrushRain {
            get {
                return ResourceManager.GetString("DefaultBrushRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales.
        /// </summary>
        internal static string DefaultBrushScales {
            get {
                return ResourceManager.GetString("DefaultBrushScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Dots.
        /// </summary>
        internal static string DefaultBrushSmallDots {
            get {
                return ResourceManager.GetString("DefaultBrushSmallDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        internal static string DefaultBrushSmoke {
            get {
                return ResourceManager.GetString("DefaultBrushSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark.
        /// </summary>
        internal static string DefaultBrushSpark {
            get {
                return ResourceManager.GetString("DefaultBrushSpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiral.
        /// </summary>
        internal static string DefaultBrushSpiral {
            get {
                return ResourceManager.GetString("DefaultBrushSpiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string DefaultBrushSquare {
            get {
                return ResourceManager.GetString("DefaultBrushSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Brush.
        /// </summary>
        internal static string DeleteBrush {
            get {
                return ResourceManager.GetString("DeleteBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the current brush. Current brush settings are unaffected..
        /// </summary>
        internal static string DeleteBrushTip {
            get {
                return ResourceManager.GetString("DeleteBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkerboard Dithering.
        /// </summary>
        internal static string DitherDraw {
            get {
                return ResourceManager.GetString("DitherDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only draw every other pixel, in a checkerboard pattern. Useful for pixel art..
        /// </summary>
        internal static string DitherDrawTip {
            get {
                return ResourceManager.GetString("DitherDrawTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        internal static string HueAbbr {
            get {
                return ResourceManager.GetString("HueAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Jitter:.
        /// </summary>
        internal static string JitterBlue {
            get {
                return ResourceManager.GetString("JitterBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the color will randomly shift so it will sometimes be normal and sometimes up to this much less or more blue..
        /// </summary>
        internal static string JitterBlueTip {
            get {
                return ResourceManager.GetString("JitterBlueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Jitter:.
        /// </summary>
        internal static string JitterGreen {
            get {
                return ResourceManager.GetString("JitterGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the color will randomly shift so it will sometimes be normal and sometimes up to this much less or more green..
        /// </summary>
        internal static string JitterGreenTip {
            get {
                return ResourceManager.GetString("JitterGreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Jitter:.
        /// </summary>
        internal static string JitterHue {
            get {
                return ResourceManager.GetString("JitterHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the hue will randomly shift based on the provided amounts..
        /// </summary>
        internal static string JitterHueTip {
            get {
                return ResourceManager.GetString("JitterHueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Jitter:.
        /// </summary>
        internal static string JitterRed {
            get {
                return ResourceManager.GetString("JitterRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the color will randomly shift so it will sometimes be normal and sometimes up to this much less or more red..
        /// </summary>
        internal static string JitterRedTip {
            get {
                return ResourceManager.GetString("JitterRedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat. Jitter:.
        /// </summary>
        internal static string JitterSaturation {
            get {
                return ResourceManager.GetString("JitterSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the grayness will randomly shift based on the provided amounts..
        /// </summary>
        internal static string JitterSaturationTip {
            get {
                return ResourceManager.GetString("JitterSaturationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Jitter:.
        /// </summary>
        internal static string JitterValue {
            get {
                return ResourceManager.GetString("JitterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brightness will randomly shift based on the provided amounts..
        /// </summary>
        internal static string JitterValueTip {
            get {
                return ResourceManager.GetString("JitterValueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default Brush Images?.
        /// </summary>
        internal static string LoadDefaultBrushes {
            get {
                return ResourceManager.GetString("LoadDefaultBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned off, only the circle brush image and custom brush images will be loaded..
        /// </summary>
        internal static string LoadDefaultBrushesTip {
            get {
                return ResourceManager.GetString("LoadDefaultBrushesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Alpha.
        /// </summary>
        internal static string LockAlpha {
            get {
                return ResourceManager.GetString("LockAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserves transparency so no brush strokes affect the transparency of the pixels..
        /// </summary>
        internal static string LockAlphaTip {
            get {
                return ResourceManager.GetString("LockAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize window?.
        /// </summary>
        internal static string MaximizeWindow {
            get {
                return ResourceManager.GetString("MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to maximize the window or not. Click to toggle..
        /// </summary>
        internal static string MaximizeWindowTip {
            get {
                return ResourceManager.GetString("MaximizeWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Draw Distance.
        /// </summary>
        internal static string MinDrawDistance {
            get {
                return ResourceManager.GetString("MinDrawDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each brush stroke must be at least this far apart to have an effect. Used, for example, to make lines. Draws lines when set to high values when brush density is not zero..
        /// </summary>
        internal static string MinDrawDistanceTip {
            get {
                return ResourceManager.GetString("MinDrawDistanceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shortcut.
        /// </summary>
        internal static string NoShortcut {
            get {
                return ResourceManager.GetString("NoShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and finish..
        /// </summary>
        internal static string OkTip {
            get {
                return ResourceManager.GetString("OkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate With Mouse.
        /// </summary>
        internal static string OrientToMouse {
            get {
                return ResourceManager.GetString("OrientToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, the brush rotates with the mouse. If the brush appears to point to the right, it will look accurate. If it does not, try adjusting rotation to fix it..
        /// </summary>
        internal static string OrientToMouseTip {
            get {
                return ResourceManager.GetString("OrientToMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Spray:.
        /// </summary>
        internal static string RandHorzShift {
            get {
                return ResourceManager.GetString("RandHorzShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved left or right this much..
        /// </summary>
        internal static string RandHorzShiftTip {
            get {
                return ResourceManager.GetString("RandHorzShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Size:.
        /// </summary>
        internal static string RandMaxSize {
            get {
                return ResourceManager.GetString("RandMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much bigger..
        /// </summary>
        internal static string RandMaxSizeTip {
            get {
                return ResourceManager.GetString("RandMaxSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Alpha:.
        /// </summary>
        internal static string RandMinAlpha {
            get {
                return ResourceManager.GetString("RandMinAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush transparency will randomly shift so it will sometimes be normal and sometimes up to this much more transparent..
        /// </summary>
        internal static string RandMinAlphaTip {
            get {
                return ResourceManager.GetString("RandMinAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Size:.
        /// </summary>
        internal static string RandMinSize {
            get {
                return ResourceManager.GetString("RandMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the size of the brush will randomly jitter so it will sometimes be normal size and sometimes up to this much smaller..
        /// </summary>
        internal static string RandMinSizeTip {
            get {
                return ResourceManager.GetString("RandMinSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Left:.
        /// </summary>
        internal static string RandRotLeft {
            get {
                return ResourceManager.GetString("RandRotLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the left..
        /// </summary>
        internal static string RandRotLeftTip {
            get {
                return ResourceManager.GetString("RandRotLeftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Right:.
        /// </summary>
        internal static string RandRotRight {
            get {
                return ResourceManager.GetString("RandRotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly rotate so it will sometimes be angled this much to the right..
        /// </summary>
        internal static string RandRotRightTip {
            get {
                return ResourceManager.GetString("RandRotRightTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spray:.
        /// </summary>
        internal static string RandVertShift {
            get {
                return ResourceManager.GetString("RandVertShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush will randomly be moved up or down this much..
        /// </summary>
        internal static string RandVertShiftTip {
            get {
                return ResourceManager.GetString("RandVertShiftTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be found for redo..
        /// </summary>
        internal static string RedoFileNotFoundError {
            get {
                return ResourceManager.GetString("RedoFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo Shortcut: Ctrl + Y. Restores changes removed by undo, if possible..
        /// </summary>
        internal static string RedoTip {
            get {
                return ResourceManager.GetString("RedoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers the canvas at 100% zoom, unrotated. (Doesn&apos;t affect the image.).
        /// </summary>
        internal static string ResetCanvas {
            get {
                return ResourceManager.GetString("ResetCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Rotation:.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string SatAbbr {
            get {
                return ResourceManager.GetString("SatAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Brush.
        /// </summary>
        internal static string SaveNewBrush {
            get {
                return ResourceManager.GetString("SaveNewBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current brush settings as a brush under a unique name..
        /// </summary>
        internal static string SaveNewBrushTip {
            get {
                return ResourceManager.GetString("SaveNewBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all changes in the preferences..
        /// </summary>
        internal static string SavePreferencesTip {
            get {
                return ResourceManager.GetString("SavePreferencesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seamless Drawing.
        /// </summary>
        internal static string SeamlessDrawing {
            get {
                return ResourceManager.GetString("SeamlessDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When activated, brush strokes that clip at the edges of the canvas will &quot;wrap around&quot; to the other side, such that if the image was tiled, it would look smoothly continuous..
        /// </summary>
        internal static string SeamlessDrawingTip {
            get {
                return ResourceManager.GetString("SeamlessDrawingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press new key....
        /// </summary>
        internal static string SetShortcutText {
            get {
                return ResourceManager.GetString("SetShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings folder could not be located. Your settings may not be loaded or saved..
        /// </summary>
        internal static string SettingsUnavailableError {
            get {
                return ResourceManager.GetString("SettingsUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Shift:.
        /// </summary>
        internal static string ShiftAlpha {
            get {
                return ResourceManager.GetString("ShiftAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will change transparency by this much..
        /// </summary>
        internal static string ShiftAlphaTip {
            get {
                return ResourceManager.GetString("ShiftAlphaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Shift:.
        /// </summary>
        internal static string ShiftRotation {
            get {
                return ResourceManager.GetString("ShiftRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush will tilt by this much..
        /// </summary>
        internal static string ShiftRotationTip {
            get {
                return ResourceManager.GetString("ShiftRotationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Shift:.
        /// </summary>
        internal static string ShiftSize {
            get {
                return ResourceManager.GetString("ShiftSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time a brush stroke is applied, the brush size will change by this much..
        /// </summary>
        internal static string ShiftSizeTip {
            get {
                return ResourceManager.GetString("ShiftSizeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Transparency.
        /// </summary>
        internal static string ShortcutAlpha {
            get {
                return ResourceManager.GetString("ShortcutAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Shift.
        /// </summary>
        internal static string ShortcutAlphaShift {
            get {
                return ResourceManager.GetString("ShortcutAlphaShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend Mode.
        /// </summary>
        internal static string ShortcutBlendMode {
            get {
                return ResourceManager.GetString("ShortcutBlendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Smoothing.
        /// </summary>
        internal static string ShortcutBrushSmoothing {
            get {
                return ResourceManager.GetString("ShortcutBrushSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Zoom.
        /// </summary>
        internal static string ShortcutCanvasZoom {
            get {
                return ResourceManager.GetString("ShortcutCanvasZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Influence.
        /// </summary>
        internal static string ShortcutColorInfluence {
            get {
                return ResourceManager.GetString("ShortcutColorInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize Brush.
        /// </summary>
        internal static string ShortcutColorizeBrush {
            get {
                return ResourceManager.GetString("ShortcutColorizeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Stroke Density.
        /// </summary>
        internal static string ShortcutDensity {
            get {
                return ResourceManager.GetString("ShortcutDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string ShortcutIntentBoolFalse {
            get {
                return ResourceManager.GetString("ShortcutIntentBoolFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string ShortcutIntentBoolToggle {
            get {
                return ResourceManager.GetString("ShortcutIntentBoolToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string ShortcutIntentBoolTrue {
            get {
                return ResourceManager.GetString("ShortcutIntentBoolTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ShortcutIntentNumAdd {
            get {
                return ResourceManager.GetString("ShortcutIntentNumAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add (wrap around).
        /// </summary>
        internal static string ShortcutIntentNumAddWrap {
            get {
                return ResourceManager.GetString("ShortcutIntentNumAddWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string ShortcutIntentNumSet {
            get {
                return ResourceManager.GetString("ShortcutIntentNumSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string ShortcutIntentNumSub {
            get {
                return ResourceManager.GetString("ShortcutIntentNumSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract (wrap around).
        /// </summary>
        internal static string ShortcutIntentNumSubWrap {
            get {
                return ResourceManager.GetString("ShortcutIntentNumSubWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Jitter Max.
        /// </summary>
        internal static string ShortcutJitterBlueMax {
            get {
                return ResourceManager.GetString("ShortcutJitterBlueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Jitter Min.
        /// </summary>
        internal static string ShortcutJitterBlueMin {
            get {
                return ResourceManager.GetString("ShortcutJitterBlueMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Jitter Max.
        /// </summary>
        internal static string ShortcutJitterGreenMax {
            get {
                return ResourceManager.GetString("ShortcutJitterGreenMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Jitter Min.
        /// </summary>
        internal static string ShortcutJitterGreenMin {
            get {
                return ResourceManager.GetString("ShortcutJitterGreenMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Spray.
        /// </summary>
        internal static string ShortcutJitterHorSpray {
            get {
                return ResourceManager.GetString("ShortcutJitterHorSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Jitter Max.
        /// </summary>
        internal static string ShortcutJitterHueMax {
            get {
                return ResourceManager.GetString("ShortcutJitterHueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Jitter Min.
        /// </summary>
        internal static string ShortcutJitterHueMin {
            get {
                return ResourceManager.GetString("ShortcutJitterHueMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Max Size.
        /// </summary>
        internal static string ShortcutJitterMaxSize {
            get {
                return ResourceManager.GetString("ShortcutJitterMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Alpha.
        /// </summary>
        internal static string ShortcutJitterMinAlpha {
            get {
                return ResourceManager.GetString("ShortcutJitterMinAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Min Size.
        /// </summary>
        internal static string ShortcutJitterMinSize {
            get {
                return ResourceManager.GetString("ShortcutJitterMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Jitter Max.
        /// </summary>
        internal static string ShortcutJitterRedMax {
            get {
                return ResourceManager.GetString("ShortcutJitterRedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Jitter Min.
        /// </summary>
        internal static string ShortcutJitterRedMin {
            get {
                return ResourceManager.GetString("ShortcutJitterRedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Left.
        /// </summary>
        internal static string ShortcutJitterRotLeft {
            get {
                return ResourceManager.GetString("ShortcutJitterRotLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Rot to Right.
        /// </summary>
        internal static string ShortcutJitterRotRight {
            get {
                return ResourceManager.GetString("ShortcutJitterRotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation Jitter Max.
        /// </summary>
        internal static string ShortcutJitterSatMax {
            get {
                return ResourceManager.GetString("ShortcutJitterSatMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation Jitter Min.
        /// </summary>
        internal static string ShortcutJitterSatMin {
            get {
                return ResourceManager.GetString("ShortcutJitterSatMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Jitter Max.
        /// </summary>
        internal static string ShortcutJitterValueMax {
            get {
                return ResourceManager.GetString("ShortcutJitterValueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Jitter Min.
        /// </summary>
        internal static string ShortcutJitterValueMin {
            get {
                return ResourceManager.GetString("ShortcutJitterValueMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Spray.
        /// </summary>
        internal static string ShortcutJitterVerSpray {
            get {
                return ResourceManager.GetString("ShortcutJitterVerSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string ShortcutRotation {
            get {
                return ResourceManager.GetString("ShortcutRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Shift.
        /// </summary>
        internal static string ShortcutRotShift {
            get {
                return ResourceManager.GetString("ShortcutRotShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Brush.
        /// </summary>
        internal static string ShortcutSelectedBrush {
            get {
                return ResourceManager.GetString("ShortcutSelectedBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Brush Image.
        /// </summary>
        internal static string ShortcutSelectedBrushImage {
            get {
                return ResourceManager.GetString("ShortcutSelectedBrushImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tool.
        /// </summary>
        internal static string ShortcutSelectedTool {
            get {
                return ResourceManager.GetString("ShortcutSelectedTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ShortcutSize {
            get {
                return ResourceManager.GetString("ShortcutSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Shift.
        /// </summary>
        internal static string ShortcutSizeShift {
            get {
                return ResourceManager.GetString("ShortcutSizeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry Mode.
        /// </summary>
        internal static string ShortcutSymmetryMode {
            get {
                return ResourceManager.GetString("ShortcutSymmetryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Size:.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing: High.
        /// </summary>
        internal static string SmoothingHigh {
            get {
                return ResourceManager.GetString("SmoothingHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing: Jagged.
        /// </summary>
        internal static string SmoothingJagged {
            get {
                return ResourceManager.GetString("SmoothingJagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing: Normal.
        /// </summary>
        internal static string SmoothingNormal {
            get {
                return ResourceManager.GetString("SmoothingNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 10-point.
        /// </summary>
        internal static string Symmetry10pt {
            get {
                return ResourceManager.GetString("Symmetry10pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 11-point.
        /// </summary>
        internal static string Symmetry11pt {
            get {
                return ResourceManager.GetString("Symmetry11pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 12-point.
        /// </summary>
        internal static string Symmetry12pt {
            get {
                return ResourceManager.GetString("Symmetry12pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 3-point.
        /// </summary>
        internal static string Symmetry3pt {
            get {
                return ResourceManager.GetString("Symmetry3pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 4-point.
        /// </summary>
        internal static string Symmetry4pt {
            get {
                return ResourceManager.GetString("Symmetry4pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 5-point.
        /// </summary>
        internal static string Symmetry5pt {
            get {
                return ResourceManager.GetString("Symmetry5pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 6-point.
        /// </summary>
        internal static string Symmetry6pt {
            get {
                return ResourceManager.GetString("Symmetry6pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 7-point.
        /// </summary>
        internal static string Symmetry7pt {
            get {
                return ResourceManager.GetString("Symmetry7pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 8-point.
        /// </summary>
        internal static string Symmetry8pt {
            get {
                return ResourceManager.GetString("Symmetry8pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: 9-point.
        /// </summary>
        internal static string Symmetry9pt {
            get {
                return ResourceManager.GetString("Symmetry9pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: Both.
        /// </summary>
        internal static string SymmetryBoth {
            get {
                return ResourceManager.GetString("SymmetryBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: Horizontal.
        /// </summary>
        internal static string SymmetryHorizontal {
            get {
                return ResourceManager.GetString("SymmetryHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: None.
        /// </summary>
        internal static string SymmetryNone {
            get {
                return ResourceManager.GetString("SymmetryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: At Points.
        /// </summary>
        internal static string SymmetrySetPoints {
            get {
                return ResourceManager.GetString("SymmetrySetPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While drawing, the brush can be mirrored horizontally and/or vertically..
        /// </summary>
        internal static string SymmetryTip {
            get {
                return ResourceManager.GetString("SymmetryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry: Vertical.
        /// </summary>
        internal static string SymmetryVertical {
            get {
                return ResourceManager.GetString("SymmetryVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Pressure.
        /// </summary>
        internal static string TabPressure {
            get {
                return ResourceManager.GetString("TabPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string TabPressureSetting {
            get {
                return ResourceManager.GetString("TabPressureSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Draw.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Shortcut: B. Activate this tool to draw with the chosen brush and its settings..
        /// </summary>
        internal static string ToolBrushTip {
            get {
                return ResourceManager.GetString("ToolBrushTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser Shortcut: E. Activate this tool to erase with the chosen brush and its settings, revealing the original image..
        /// </summary>
        internal static string ToolEraserTip {
            get {
                return ResourceManager.GetString("ToolEraserTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Origin Shortcut: O. Activate this tool to change the symmetry origin..
        /// </summary>
        internal static string ToolOriginTip {
            get {
                return ResourceManager.GetString("ToolOriginTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Shortcut: Ctrl + Z. Undo the last drawing, if possible..
        /// </summary>
        internal static string UndoTip {
            get {
                return ResourceManager.GetString("UndoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Val.
        /// </summary>
        internal static string ValAbbr {
            get {
                return ResourceManager.GetString("ValAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the associated number will influence the setting for full pressure on a drawing tablet. Partial pressure will also influence the setting to a proportionally smaller degree (on a linear curve)..
        /// </summary>
        internal static string ValueInfluenceTip {
            get {
                return ResourceManager.GetString("ValueInfluenceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as number.
        /// </summary>
        internal static string ValueTypeAdd {
            get {
                return ResourceManager.GetString("ValueTypeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as percent of max.
        /// </summary>
        internal static string ValueTypeAddPercent {
            get {
                return ResourceManager.GetString("ValueTypeAddPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as percent of self.
        /// </summary>
        internal static string ValueTypeAddPercentCurrent {
            get {
                return ResourceManager.GetString("ValueTypeAddPercentCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as percent of self: At full pressure, the setting equals itself plus this percent of itself, e.g. 30% when the setting is 50 would make the setting 65..
        /// </summary>
        internal static string ValueTypeAddPercentCurrentTip {
            get {
                return ResourceManager.GetString("ValueTypeAddPercentCurrentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as percent of max: At full value, the setting equals itself plus this percent of the max possible value it can have, e.g. if the setting is 50 out of 200 and the percent is 30%, at full pressure the setting would be 110..
        /// </summary>
        internal static string ValueTypeAddPercentTip {
            get {
                return ResourceManager.GetString("ValueTypeAddPercentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as number: At full pressure, the setting equals itself plus this number..
        /// </summary>
        internal static string ValueTypeAddTip {
            get {
                return ResourceManager.GetString("ValueTypeAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the percent of max.
        /// </summary>
        internal static string ValueTypeMatchPercent {
            get {
                return ResourceManager.GetString("ValueTypeMatchPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the percent of max: At full pressure, the setting equals this percent of the max possible value it can have, e.g. 30% of 200 at full pressure would make the setting 60..
        /// </summary>
        internal static string ValueTypeMatchPercentTip {
            get {
                return ResourceManager.GetString("ValueTypeMatchPercentTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the number.
        /// </summary>
        internal static string ValueTypeMatchValue {
            get {
                return ResourceManager.GetString("ValueTypeMatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the number: At full pressure, the setting equals this number..
        /// </summary>
        internal static string ValueTypeMatchValueTip {
            get {
                return ResourceManager.GetString("ValueTypeMatchValueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in use.
        /// </summary>
        internal static string ValueTypeNothing {
            get {
                return ResourceManager.GetString("ValueTypeNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in use: Tablet pressure doesn&apos;t affect anything..
        /// </summary>
        internal static string ValueTypeNothingTip {
            get {
                return ResourceManager.GetString("ValueTypeNothingTip", resourceCulture);
            }
        }
    }
}
